services:
  wallabag:
    image: wallabag/wallabag
    environment:
      # - MYSQL_ROOT_PASSWORD=wallaroot
      # - SYMFONY__ENV__DATABASE_DRIVER=pdo_sqlite
      # - SYMFONY__ENV__DATABASE_HOST=db
      # - SYMFONY__ENV__DATABASE_PORT=3306
      # - SYMFONY__ENV__DATABASE_NAME=wallabag
      # - SYMFONY__ENV__DATABASE_USER=wallabag
      # - SYMFONY__ENV__DATABASE_PASSWORD=wallapass
      # - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      # - SYMFONY__ENV__DATABASE_TABLE_PREFIX="wallabag_"
      # - SYMFONY__ENV__MAILER_DSN=smtp://127.0.0.1
      # - SYMFONY__ENV__FROM_EMAIL=wallabag@example.com
      - SYMFONY__ENV__DOMAIN_NAME=https://your-wallabag-instance.wallabag.org
      - SYMFONY__ENV__SERVER_NAME="Your wallabag instance"
      # - SYMFONY__ENV__SECRET="ovmpmAWXRCabNlMgzlzFXDYmCFfzGv"
      # - SYMFONY__ENV__FOSUSER_REGISTRATION=true
      # - SYMFONY__ENV__FOSUSER_CONFIRMATION=true
    ports:
      - "127.0.0.1:3008:80"
    volumes:
      - ./wallabag/data:/var/www/wallabag/data
      - ./wallabag/images:/var/www/wallabag/web/assets/images
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost",
        ]
      interval: 1m
      timeout: 3s
    depends_on:
      # - db
      - redis

  # db:
  #   image: mariadb
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=wallaroot
  #   volumes:
  #     - /opt/wallabag/data:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #     interval: 20s
  #     timeout: 3s

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
