services:

  pihole:
    container_name: pihole
    domainname: "${DOMAIN}"
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      - TZ='Europe/Moscow'
      - WEBPASSWORD
      - DNS1='1.1.1.1'
      - DNS2='1.0.0.1'
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
    # Volumes store your data between container upgrades
    volumes:
      - etc:/etc/pihole/
      - etc:/etc/dnsmasq.d/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

volumes:
  etc:
