version: '3'

services:
  bitwarden:
    image: bitwardenrs/server:latest
    restart: unless-stopped
    volumes:
      - ./bw_data:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - LOG_FILE=/data/bitwarden.log
      - WEBSOCKET_ENABLED=true            # required for websockets
      - SHOW_PASSWORD_HINT=false
      - DOMAIN=https://${DOMAIN}          # DOMAIN is set in .env but doesn't have protocol prefix
      - SMTP_FROM_NAME=Bitwarden (${DOMAIN})
      - IP_HEADER=X-Forwarded-For
      - ADMIN_TOKEN                       # Value-less variables are set in .env
      - SIGNUPS_ALLOWED
      - SIGNUPS_VERIFY
      - SMTP_HOST
      - SMTP_FROM
      - SMTP_PORT
      - SMTP_SSL
      - SMTP_USERNAME
      - SMTP_PASSWORD
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      # - traefik.http.routers.bitwarden-ui-https.rule=Host(`${DOMAIN}`)
      # - traefik.http.routers.bitwarden-ui-https.entrypoints=websecure
      # - traefik.http.routers.bitwarden-ui-https.tls=true
      # - traefik.http.routers.bitwarden-ui-https.service=bitwarden-ui
      - traefik.http.routers.bitwarden-ui-http.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.bitwarden-ui-http.entrypoints=web
      - traefik.http.routers.bitwarden-ui-http.service=bitwarden-ui
      - traefik.http.services.bitwarden-ui.loadbalancer.server.port=80
      # - traefik.http.routers.bitwarden-websocket-https.rule=Host(`${DOMAIN}`) && Path(`/notifications/hub`)
      # - traefik.http.routers.bitwarden-websocket-https.entrypoints=websecure
      # - traefik.http.routers.bitwarden-websocket-https.tls=true
      # - traefik.http.routers.bitwarden-websocket-https.service=bitwarden-websocket
      - traefik.http.routers.bitwarden-websocket-http.rule=Host(`${DOMAIN}`) && Path(`/notifications/hub`)
      - traefik.http.routers.bitwarden-websocket-http.entrypoints=web
      - traefik.http.routers.bitwarden-websocket-http.service=bitwarden-websocket
      - traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012
networks:
  web:
    external: true

