version: '3'

services:
  bitwarden:
    image: bitwardenrs/server:latest
    restart: always
    restart: unless-stopped
    volumes:
      - ./bw_data:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_DOMAINS_WHITELIST=juev.org
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      # Entry Point for https
      - "traefik.http.routers.bitwarden-secure.entrypoints=websecure"
      - "traefik.http.routers.bitwarden-secure.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.bitwarden-secure.rule=Host(`bw.juev.org`)"
      - "traefik.http.routers.bitwarden-secure.service=bitwarden-service"
      - "traefik.http.services.bitwarden-service.loadbalancer.server.port=80"
      # websocket
      - "traefik.http.routers.bitwarden-ws.entrypoints=websecure"
      - "traefik.http.routers.bitwarden-ws.rule=Host(`bw.juev.org`) && Path(`/notifications/hub`)"
      - "traefik.http.middlewares.bitwarden-ws=bw-stripPrefix@file"
      - "traefik.http.routers.bitwarden-ws.service=bitwarden-websocket"
      - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012"
networks:
  web:
    external: true

