---
version: "3"
services:
  pihole:
    container_name: pihole
    domainname: "pi.juev.org"
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      TZ: 'Europe/Moscow'
      WEBPASSWORD: "${WEBPASSWORD}"
      DNS1: '1.1.1.1'
      DNS2: '1.0.0.1'
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: "pi.juev.org"
      VIRTUAL_PORT: 80
    # Volumes store your data between container upgrades
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
       - '/etc/localtime:/etc/localtime:ro'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.http.routers.pihole.rule=Host(`pi.juev.org`)"
      - "traefik.enable=true"
      - "traefik.backend=pihole"
      - "traefik.docker.network=web"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls.certresolver=mydnschallenge"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
networks:
  web:
    external: true
