services:

  caddy:
    image: juev-caddy:latest
    build: ./
    restart: unless-stopped
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  caddy_data:
  caddy_config:
