services:

  freshrss:
    image: freshrss/freshrss:edge
    container_name: freshrss
    restart: always
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
      - ./config.custom.php:/var/www/FreshRSS/data/config.custom.php
      - ./config-user.custom.php:/var/www/FreshRSS/data/config-user.custom.php
    ports:
      - "8080:80"
    environment:
      TZ: Europe/Moscow
      CRON_MIN: '2,32'
      LISTEN: 0.0.0.0:80
      # TRUSTED_PROXY: 172.16.0.1/12 192.168.0.1/16
