version: '3'

services:

  shiori:
    image: ghcr.io/go-shiori/shiori
    volumes:
      # - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data:/shiori
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN
    command: 'tunnel run'
    restart: always
    read_only: true
    user: root
    depends_on:
      - shiori
