version: '3'

services:
  miniflux:
    image: miniflux/miniflux:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS
      - CREATE_ADMIN
      - ADMIN_USERNAME
      - ADMIN_PASSWORD
      - POLLING_FREQUENCY=10
      - POCKET_CONSUMER_KEY
      - BASE_URL=https://reader.example.org
      - TZ=Europe/Moscow

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=miniflux
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s

  cloudflared:
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN
    command: 'tunnel run'
    restart: always
    read_only: true
    user: root
    depends_on:
      - miniflux
