version: '3.4'
services:
  miniflux:
    image: miniflux/miniflux:latest
    restart: unless-stopped
    #ports:
    #  - "127.0.0.1:8080:8080"
    dns:
      - 8.8.8.8
      - 9.9.9.9
    depends_on:
      - db
    networks:
      - back
      - caddy-network
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - TZ=Europe/Moscow
      - ADMIN_USERNAME
      - ADMIN_PASSWORD
      - POLLING_FREQUENCY
      - POLLING_PARSING_ERROR_LIMIT
      - BASE_URL
      - POCKET_CONSUMER_KEY
      - PROXY_IMAGES
        #- POLLING_SCHEDULER
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
    networks:
      - back
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
volumes:
  miniflux-db:
networks:
  back:
  caddy-network:
    external: true