version: '3'

services:
  db:
    image:  postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - miniflux-database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal
  miniflux:
    image: miniflux/miniflux:latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME
      - ADMIN_PASSWORD
      - BASE_URL=https://${BASE_URL}
      - POCKET_CONSUMER_KEY
      - POLLING_FREQUENCY=10
      - BATCH_SIZE=500
      - WORKER_POOL_SIZE=50
      - HTTPS=1
    networks:
      - internal
      - web
    labels:
      - "traefik.http.routers.miniflux.rule=Host(`${BASE_URL}`)"
      - "traefik.enable=true"
      - "traefik.backend=miniflux"
      - "traefik.docker.network=web"
      - "traefik.port=8080"
      # - "traefik.http.routers.miniflux.entrypoints=websecure"
      # - "traefik.http.routers.miniflux.tls.certresolver=mydnschallenge"
networks:
  internal:
    ipam:
      config:
        - subnet: 172.16.22.0/24
  web:
    external: true

volumes:
  miniflux-database:
