services:

  baikal:
    image: ckulka/baikal:nginx
    restart: always
    ports:
     - "127.0.0.1:8083:80"
    volumes:
      - config:/var/www/baikal/config
      - data:/var/www/baikal/Specific

volumes:
  config:
  data:
