services:

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: root
    volumes:
      - ./data/config:/config
      - ./data/cache:/cache
      - type: bind
        source: ./data/media
        target: /media
    restart: always
