services:

  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:latest
    volumes:
      - "${LD_HOST_DATA_DIR:-./data}:/etc/linkding/data"
    restart: always
    ports:
      - "127.0.0.1:3006:9090"
