services:
  v2ray:
    image: v2fly/v2fly-core
    restart: always
    container_name: v2fly-core
    ports:
      - "1080:1080/tcp"
      - "1080:1080/udp"
      - "8080:8080"
    entrypoint: ["/usr/bin/v2ray", "run", "-c", "/etc/v2fly/config.json"]
    volumes:
      - ./config.json:/etc/v2fly/config.json