services:

  forgejo:
    image: codeberg.org/forgejo/forgejo:1.21
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./data:/data
      - ./config:/etc/gitea
      - /etc/localtime:/etc/localtime:ro
