services:

  yarr:
    build: .
    container_name: yarr
    user: root
    volumes:
      - ./data:/data
    restart: always
    ports:
      - "7070:7070"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
