version: '3'

services:
  shiori:
    image: radhifadlillah/shiori
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - shiori:/srv/shiori
    environment:
      - SHIORI_DIR=/srv/shiori
    networks:
      - web
    restart: unless-stopped
    labels:
      - "traefik.http.routers.shiori.rule=Host(`${DOMAIN}`)"
      - "traefik.enable=true"
      - "traefik.backend=shiori"
      - "traefik.docker.network=web"
      # - "traefik.http.routers.shiori.entrypoints=websecure"
      # - "traefik.http.routers.shiori.tls.certresolver=mydnschallenge"
networks:
  web:
    external: true

volumes:
  shiori:
