services:
  headscale:
    container_name: headscale
    image: headscale/headscale:latest
    restart: unless-stopped
    # ports:
    # - 8080:8080
    volumes:
      - ./config:/etc/headscale
      - ./data:/var/lib/headscale
    entrypoint: headscale serve

  headscale-ui:
    container_name: headscale-ui
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped

  caddy:
    # image: caddy:alpine
    build: .
    restart: unless-stopped
    ports:
      # - "80:80"
      - "8443:8443"
      - "8443:8443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CF_API_TOKEN=token

volumes:
  caddy_data:
  caddy_config:
