version: '3'
services:
  webdav:
    image: bytemark/webdav
    container_name: webdav
    restart: always
    environment:
      AUTH_TYPE: Digest
      USERNAME: "${USERNAME}"
      PASSWORD: "${PASSWORD}"
    volumes:
      - $PWD/dav:/var/lib/dav
      - /etc/localtime:/etc/localtime:ro
    networks:
      - web
    labels:
      - "traefik.http.routers.webdav.rule=Host(`dav.juev.org`)"
      - "traefik.enable=true"
      - "traefik.backend=webdav"
      - "traefik.docker.network=web"
networks:
  web:
    external: true
