version: '3'
services:

  webdav:
    image: bytemark/webdav
    restart: always
    environment:
      - AUTH_TYPE
      - USERNAME
      - PASSWORD
    volumes:
      - ./dav:/var/lib/dav
      #- /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  cloudflared:
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN
    command: 'tunnel run'
    restart: always
    read_only: true
    user: root
    depends_on:
      - webdav
