services:
  bitlbee:
    build: .
    image: mbologna/docker-bitlbee
    container_name: bitlbee
    restart: always
    #ports:
    #  - 6667:6667
    volumes:
      - ./etc/bitlbee:/usr/local/etc/bitlbee
      - bitlbee_data:/var/lib/bitlbee
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  znc:
    image: lscr.io/linuxserver/znc:latest
    container_name: znc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - ./znc:/config
    ports:
      - 6501:6501
    restart: unless-stopped

volumes:
  bitlbee_data:
