version: '3'
services:
  mtg:
    image: 'nineseconds/mtg:stable'
    restart: always
    ports:
      - "3128:3128"
      - "3129:3129"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DETAILED_LOGGING=true
    labels:
      - "traefik.http.routers.mtg.rule=Host(`mtg.juev.org`)"
      - "traefik.enable=true"
      - "traefik.backend=mtg"
      - "traefik.docker.network=web"
      - "traefik.port=3128"
      - "traefik.http.routers.mtg.entrypoints=websecure"
      - "traefik.http.routers.mtg.tls.certresolver=mydnschallenge"