services:

  betula:
    build: .
    container_name: betula
    user: root
    volumes:
      - ./data:/data
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - "1738:1738"
