services:

  mycorrhiza:
    build: .
    container_name: mycorrhiza
    user: root
    volumes:
      - ./data:/wiki
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - "1737:1737"
