services:
  cloudflared:
    network_mode: host
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token $TUNNEL_TOKEN
    restart: always
    read_only: true
    user: root
    deploy:
      replicas: 2
