version: '3.5'
services:
  betula:
    build: .
    container_name: betula
    user: root
    volumes:
      - ./data:/data
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    # ports:
    #   - "1738:1738"

  cloudflared:
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN=token
    command: 'tunnel run'
    restart: always
    read_only: true
    user: root
    depends_on:
      - betula
